---
title: "Article Code"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 2
    highlight: tango
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# R Set up #

## Load Libraries ##
```{r load libraries, message = FALSE, warning=FALSE}
library(tidyverse)
library(tidycensus)
library(ggplot2)
library(plotly)
library(scales)
```

# Data Set Up #

## Get Data ##
```{r Get Data, message = FALSE, warning=FALSE, results = 'hide'}
FloodData <- read_csv("ChicagoFloodData.csv") %>%
  mutate(GEOID = as.numeric(AreaCode))

minGEOID <- min(FloodData$GEOID)
maxGEOID <- max(FloodData$GEOID)

CensusData <- get_acs(
  geography = "zcta",
  table = c(race = "B03002"),
  geometry = TRUE,
  cache_table = TRUE) %>% 
  filter(GEOID >= minGEOID & GEOID <= maxGEOID)

ChicagoData <- merge(CensusData, FloodData) 

```

## Clean Data ##
```{r, Clean Data, message = FALSE, warning=FALSE, results = FALSE}
ChicagoData <- ChicagoData %>% 
  mutate(Group = case_when(variable == "B03002_003" ~ 'W',
                           variable == "B03002_004" ~ 'BoHL',
                           variable == "B03002_012" ~ 'BoHL',
                           variable == "B03002_001" ~ 'D',
                           variable == "B03002_002" ~ 'D',
                           variable == "B03002_013" ~ 'D',
                           variable == "B03002_014" ~ 'D',
                           variable == "B03002_015" ~ 'D',
                           variable == "B03002_016" ~ 'D',
                           variable == "B03002_017" ~ 'D',
                           variable == "B03002_018" ~ 'D',
                           variable == "B03002_019" ~ 'D',
                           variable == "B03002_020" ~ 'D',
                           variable == "B03002_021" ~ 'D',
                           TRUE ~ 'Other'))

ChicagoDataSummary <- ChicagoData  %>% 
  filter(FloodingLikelihood == 0.2) %>%
  filter(Group != 'D') %>% 
  group_by(Group, GEOID) %>%
  summarize(NumPeople = sum(estimate), 
            PercRisk = mean(PercentAtRisk),
            FloodChance = mean(FloodChance)) %>%
  group_by(GEOID) %>%
  mutate(freq = (NumPeople/sum(NumPeople))*100,
         freq_group = case_when(
           freq >= 0 & freq < 20 ~ "0-20%",
           freq >= 20 & freq < 40 ~ "20-40%",
           freq >= 40 & freq < 60 ~ "40-60%",
           freq >= 60 & freq < 80 ~ "60-80%",
           freq >= 80 & freq <= 100 ~ "80-100%",
           TRUE ~ 'ERROR'
         )) 

ChicagoDataSummary <- ChicagoDataSummary %>%
  filter(Group == 'BoHL')

ChicagoDataSummary$quartile <- ntile(ChicagoDataSummary$FloodChance, 3)
ChicagoDataSummary <- sf::st_cast(ChicagoDataSummary, "MULTIPOLYGON")
```

# Plot Set Up #

## Themes and Variables ## 
```{r Plot Themes and Variables, message = FALSE, warning=FALSE}

point <- format_format(big.mark = ",", decimal.mark = ".", scientific = FALSE)

FONTFAMILY = "NULL"

font = list(
  size = 12,
  color = "black"
)


label = list(
  bgcolor = "white",
  bordercolor = "black",
  font = font
)

```

## Create Map ##
```{r Create Map Plot, message = FALSE, warning=FALSE}
MapPlot <- ggplot(data = ChicagoDataSummary, 
                  aes(fill = FloodChance,
                      text = paste("Zip Code:", GEOID,"\n",
                                   "Properties at Risk:", FloodChance,"\n",
                                   "Black or Hispanic Residents:", round(freq),"%"))) +
  geom_sf(color = 'black', size = .3) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1,
                       breaks = pretty_breaks(),
                       label = comma,
                       limits = c(0, 15000)) +
  labs(title = NULL,
       fill = "Properties\nat Risk") +
  theme_classic() +
  theme(
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 8),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank())

ggplotly(MapPlot, tooltip = c("text")) %>% 
  style(hoverlabel = label) %>%
  layout(
    autosize = F, 
    width = 400, 
    height = 500
  ) %>%
  config(displayModeBar = FALSE,
         showTips = TRUE)
```

## Create Scatter Plot ##
```{r Create Scatter Plot, message = FALSE, warning=FALSE}
ScatterPlot <- ggplot(ChicagoDataSummary, 
                      aes(x = freq, 
                          y = FloodChance,
                          fill = FloodChance,
                          color = FloodChance,
                          text = paste("Zip Code:", GEOID,"\n",
                                   "Properties at Risk:", FloodChance,"\n",
                                   "Black or Hispanic Residents:", round(freq),"%"))) +
  geom_point(shape=21, 
             size=4.5) +
  scale_fill_distiller(palette = "YlOrBr", 
                       direction = 1) +
  scale_color_gradient(guide = FALSE, 
                       low = "grey1", 
                       high = "black") +
  labs(title = "Flood Risk by Chicago Zip Code",
       x = "Black or Hispanic Residents",
       y = "Properties at Risk") +
  scale_x_continuous(labels =  scales::percent_format(scale = 1), 
                     breaks = pretty_breaks()) +
  scale_y_continuous(labels = point, 
                     breaks = pretty_breaks()) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 12, 
                              face = "bold"),
    axis.text = element_text(size = 9),
    axis.title = element_text(size = 11),
    strip.background.x = element_rect("grey90"),
    legend.position = "none")

ggplotly(ScatterPlot, tooltip = "text") %>% 
  style(hoverlabel = label) %>%
  layout(    
    autosize = F, 
    width = 440, 
    height = 440) %>%
  config(displayModeBar = FALSE,
         showTips = TRUE)
```

